name = "ExponentialUtilities"
uuid = "d4d017d3-3776-5f7e-afef-a10c40355c18"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "1.25.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
GenericSchur = "c145ed77-6b09-5dd9-b285-bf645a82121e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
libblastrampoline_jll = "8e850b90-86db-534c-a0d3-1478176c7d93"

[compat]
Adapt = "3.4.0, 4"
Aqua = "0.8"
ArrayInterface = "7.1"
ForwardDiff = "0.10.13"
GPUArraysCore = "0.1"
GenericSchur = "0.5.3"
LinearAlgebra = "1.9"
Pkg = "1"
PrecompileTools = "1"
Printf = "1.9"
Random = "1"
SafeTestsets = "0.1"
SparseArrays = "1.9"
StaticArrays = "1.2"
Test = "1"
julia = "1.9"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "ForwardDiff", "Pkg", "Test", "SafeTestsets", "StaticArrays", "Random"]
